

class SocketClient:
    def id(self): ...
    def connect(self): ...
    def disconnect(self): ...
    def reconnect(self): ...
    def send_event(self, event: str): ...
    def send_info(self, info: dict): ...
    def send_data(self, data: bytes): ...


class SocketServer:
    def on_connected(self): ...
    def on_disconnected(self): ...
    def on_received_event(self, event: str): ...
    def on_received_info(self, info: dict): ...
    def on_received_data(self, data: bytes): ...
